# Generated by Django 5.2.3 on 2025-09-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('games', 'Juegos'), ('anime', 'Anime'), ('series', 'Series'), ('movies', 'Peliculas'), ('animados', 'Animados'), ('novelas', 'Novelas'), ('doramas', 'Doramas')], max_length=10)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('plataform', models.CharField(blank=True, max_length=100, null=True)),
                ('seasons', models.CharField(blank=True, max_length=50, null=True)),
                ('chapters', models.CharField(blank=True, max_length=50, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='catalogos_c_name_5da10f_idx'), models.Index(fields=['type'], name='catalogos_c_type_6044b5_idx')],
            },
        ),
    ]
