# Generated by Django 5.2.3 on 2025-09-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='catalogo',
            name='catalogos_c_name_5da10f_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalogo',
            name='catalogos_c_type_6044b5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='catalogo',
            unique_together={('name', 'type')},
        ),
    ]
