# Generated by Django 5.2.3 on 2025-06-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
