# Generated by Django 5.2.3 on 2025-06-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_path_alter_file_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=80),
        ),
    ]
