# Generated by Django 5.2.3 on 2025-08-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_is_video_file_last_modified_file_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_modified',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
